#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent

request = json.load(sys.stdin)
original_environment = request['environment']

for evar in ['INSIGHTS_ENABLED', 'INSIGHTS_SERVER_URL', 'INSIGHTS_VERIFY_TLS']:
    if evar in original_environment:
        agent.set_env(evar, original_environment[evar])
